name: Compile LaTeX and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Series/Serie*.tex
            GuiaTeoricoCompleto.tex
          work_in_root_file_dir: true
          compiler: latexmk
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Create deployment directory
        run: mkdir -p dist

      - name: Move PDFs to deployment directory
        run: |
          mv Series/*.pdf dist/ 2>/dev/null || true
          mv *.pdf dist/ 2>/dev/null || true

      - name: Create index.html
        run: |
          cat << 'EOF' > dist/index.html
          <!DOCTYPE html>
          <html lang="pt">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Séries e Resumo Teórico</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; background-color: #f9f9f9; color: #333; }
                  h1 { color: #2c3e50; text-align: center; }
                  h2 { color: #2980b9; margin-top: 30px; }
                  ul { list-style-type: none; padding: 0; max-width: 600px; margin: 20px auto; }
                  li { margin: 15px 0; background: #fff; padding: 10px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
                  a { text-decoration: none; color: #2980b9; font-weight: bold; }
                  a:hover { color: #e74c3c; text-decoration: underline; }
                  p { text-align: center; }
              </style>
          </head>
          <body>
              <h1>Séries Disponíveis</h1>
              <ul>
          EOF
          for file in dist/Serie*.pdf; do
            [ -f "$file" ] || continue
            base=$(basename "$file" .pdf)
            display_name=${base/Serie/Série\ }
            echo "      <li><a href=\"${base}.pdf\">${display_name}</a></li>" >> dist/index.html
          done
          cat << 'EOF' >> dist/index.html
              </ul>
              <h2>Resumo Teórico</h2>
              <p><a href="GuiaTeoricoCompleto.pdf">Guia Teórico Completo</a></p>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
